---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-springboot-microservice-pipeline
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/kingshuknandy2016/devops-master-class
