apiVersion: tools.pongzt.com/v1alpha1
kind: GitHook
metadata:
  name: githook-sample
spec:
  gitProvider: github
  eventTypes:
  - push
  projectUrl: "https://github.com/kingshuknandy2016/devops-master-class" #replace this with your test repo
  accessToken:
    secretKeyRef:
      name: gitsecret
      key: accessToken
  secretToken:
    secretKeyRef:
      name: gitsecret
      key: secretToken
  runspec:
    pipelineRef:
      name: simple-pipeline
    serviceAccount: default